[package]
name = "bab_rs"
version = "0.1.0"
edition = "2024"
description = "An implementation of the Bab family of hash functions, and its WILLIAM3 instantiation."
license = "MIT OR Apache-2.0"

[features]

default = ["william3"]

# Provide an implementation of the WILLIAM3 parameterisation of Bab. Enabled by default.
william3 = ["dep:arrayref"]

[dependencies]
arrayref = { version = "0.3.5", optional = true }

# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
